### ISSUE TITLE
mockにてexpect()とset_callback()を両方有効化する対応について相談

### ISSUE THREAD

**Issue by yuuu** [katono/PCUnit#3]
mock機能に関して仕様の相談があります。

### 背景
mock関数にアドレスを渡して、そのアドレスに特定の値をセットするケースでset_callback()を用いますが、引数値のチェックはexpect()を利用したいケースが多々あります。しかし、現状の実装はexpect()とset_callback()の両方をテストケース内で呼び出した場合、expect()を優先する仕様となっています。(callback関数の登録は無視)

### 仕様
以上の要求を満たすべく、expect()とset_callback()の両方を実行した場合、以下動作とする修正を加えたいと考えています。

- 引数チェック：現状のexpect()と同じ動作
- 戻り値のセット：現状のexpect()と同じ動作
- callback関数：実行するが戻り値は無視
- 実行回数の判定：expect()とset_callback()のうち後に実行された値を使用(原則同じ値をセットしなければならない)

### 実装
以下にコミットしております。仕様に問題がなければ、本ブランチにてpull requestを出したいと思っています。

https://github.com/yuuu/PCUnit/commit/0046d92a928703b64a6c96369736a1ae131da01a

### サンプルプログラム
以下にコミットしております。本サンプルはpull requestの対象外とする予定です。

https://github.com/yuuu/PCUnit/commit/5fe04e5417f2550dde916d954557328c62309ca4

以上、お手数ですが確認をよろしくお願いいたします。

**Comment by katono** [comment]
ご提案ありがとうございます。
expect()とset_callback()の両方有効化の仕様の検討をしてみました。

戻り値は、callback関数の方か、expect()で設定した方かどちらを使用するか悩ましいですが、callback関数の方が柔軟に処理を設定できるので、戻り値もcallback関数の方を使用したほうがいいのではと思います。
expect()の方を使用したい積極的な理由はあるでしょうか？

それから、実行回数の設定(expected_num_calls)はexpect()の方を使用し、set_callback()の方は無視する仕様にしたいと思います。
理由は、set_callback()の方を使用すると、無効なExpectation構造体のポインタにアクセスしてしまう恐れがあるためです。

**Comment by katono** [comment]
https://github.com/katono/PCUnit/commit/106c5ef121062326ed0e2586c62b84ae06d126d0
で修正しました。
サンプルプログラムのtest_Config.cのテストコードで動作確認しました。
ご確認ください。

**Comment by yuuu** [comment]
迅速に対応いただきありがとうございます。修正確認した結果、問題は特にありませんでした。

> expect()の方を使用したい積極的な理由はあるでしょうか？

これについては私も迷ったのですが、expect()によって引数と戻り値をセットで設定する方がbetterと判断しました。callback関数にて戻り値を設定する、という仕様でも問題はありません。

> それから、実行回数の設定(expected_num_calls)はexpect()の方を使用し、set_callback()の方は無視する仕様にしたいと思います。

オーバーアクセスを防止するという観点で、その方が良いですね。ご指摘ありがとうございました。
